// campaign_ai_log.txt extractor (2026-07-25).
//
// WHY
// ---
// The AI Movement Lab's richest input is campaign_ai_log.txt, and the crash
// reporter — the only channel that brings data back from testers — did not
// collect it at all. It cannot simply attach the file: the reference log is
// 330MB across 4.39M lines.
//
// It does not need to. The analyser reads only 12 line shapes, which is 21.8% of
// the lines, and a verbatim extract of exactly those compresses to 7.5MB — inside
// a plain Discord attachment. Because the extract is verbatim and complete for
// every pattern the analyser matches, running the Lab on it produces the same
// findings as running it on the original. aiLogExtract.test.js asserts that
// against the real 330MB file rather than trusting the argument.
//
// The patterns come from AI_LOG_LINE_PATTERNS in aiMovementAnalyzer.js — never
// retyped. A hand-copied version got the faction turn header wrong on the first
// attempt (`+start` instead of `AI: <tabs>start`), which matched nothing and
// would have silently discarded every turn boundary and all faction attribution.
"use strict";

const fs = require("fs");
const zlib = require("zlib");
const readline = require("readline");
const { AI_LOG_LINE_PATTERNS } = require("./aiMovementAnalyzer.js");

// Compiled once. Anchored at line start, as the analyser's are.
const KEEP = AI_LOG_LINE_PATTERNS.map((src) => new RegExp(src));

function keepLine(line) {
  for (let i = 0; i < KEEP.length; i++) if (KEEP[i].test(line)) return true;
  return false;
}

/**
 * Stream a campaign_ai_log and return only the lines the analyser consumes.
 *
 * @param {string} logPath
 * @param {object} [opts]
 * @param {number} [opts.maxBytes]  gzip ceiling; when the extract would exceed
 *   it, the OLDEST turn blocks are dropped rather than truncating mid-file —
 *   losing the start of a campaign is far less damaging than losing the end,
 *   and cutting mid-line would corrupt the last record.
 * @param {(n:number)=>void} [opts.onProgress]  called with the line count
 * @returns {Promise<{text:string, gzip:Buffer, lines:number, keptLines:number,
 *   sourceBytes:number, extractBytes:number, gzipBytes:number,
 *   turnBlocks:number, droppedTurnBlocks:number}>}
 */
async function extractAiLog(logPath, opts = {}) {
  const maxBytes = opts.maxBytes || 8 * 1024 * 1024;
  const onProgress = typeof opts.onProgress === "function" ? opts.onProgress : null;

  const kept = [];
  const turnStarts = [];
  let lines = 0;

  await new Promise((resolve, reject) => {
    const rl = readline.createInterface({
      input: fs.createReadStream(logPath, { encoding: "latin1" }),
      crlfDelay: Infinity,
    });
    rl.on("line", (line) => {
      lines++;
      if (onProgress && (lines % 500000) === 0) onProgress(lines);
      if (!keepLine(line)) return;
      // pattern 0 is the faction turn header — remember where each block begins
      if (KEEP[0].test(line)) turnStarts.push(kept.length);
      kept.push(line);
    });
    rl.on("close", resolve);
    rl.on("error", reject);
  });

  let from = 0;
  let droppedTurnBlocks = 0;
  let text = kept.join("\n");
  let gzip = zlib.gzipSync(Buffer.from(text, "latin1"), { level: 9 });

  // Trim whole turn blocks off the FRONT until it fits. Halving the retained
  // blocks each time keeps this to a handful of gzip passes even on a huge log.
  let blocksKept = turnStarts.length;
  while (gzip.length > maxBytes && blocksKept > 1) {
    blocksKept = Math.floor(blocksKept / 2);
    from = turnStarts[turnStarts.length - blocksKept];
    droppedTurnBlocks = turnStarts.length - blocksKept;
    text = kept.slice(from).join("\n");
    gzip = zlib.gzipSync(Buffer.from(text, "latin1"), { level: 9 });
  }

  const sourceBytes = (() => { try { return fs.statSync(logPath).size; } catch { return 0; } })();
  return {
    text, gzip,
    lines,
    keptLines: kept.length - from,
    sourceBytes,
    extractBytes: Buffer.byteLength(text, "latin1"),
    gzipBytes: gzip.length,
    turnBlocks: turnStarts.length - droppedTurnBlocks,
    droppedTurnBlocks,
  };
}

/**
 * The same patterns rendered as a Python source fragment, so the crash reporter
 * can filter with them without a second hand-typed copy. Written into the
 * reporter's bundle by scripts/gen-ailog-patterns.js.
 */
function pythonPatternModule() {
  const body = AI_LOG_LINE_PATTERNS.map((src) => `    r"""${src}""",`).join("\n");
  return `# GENERATED by scripts/gen-ailog-patterns.js — DO NOT EDIT BY HAND.
#
# The line shapes Provincia's AI Movement Lab reads out of campaign_ai_log.txt,
# exported from AI_RX in src/aiMovementAnalyzer.js so the reporter's filter can
# never drift from the analyser's. A drifted copy would silently drop data with
# no error — the first hand-written version guessed the faction turn header as
# "+start" instead of "AI: <tabs>start" and matched nothing at all.
#
# JavaScript and Python regex syntax agree for every construct used here
# (anchors, \\t, character classes, escaped parens, \\d, \\w, \\S, +, *, ?).
# scripts/gen-ailog-patterns.js asserts that before writing this file.
import re

AI_LOG_LINE_PATTERNS = [
${body}
]

_COMPILED = [re.compile(p) for p in AI_LOG_LINE_PATTERNS]


def keep_ai_log_line(line: str) -> bool:
    """True when Provincia's analyser would read this line.

    search(), NOT match(). JavaScript's RegExp.test() scans the whole string; the
    patterns that must be anchored carry their own leading ^. Python's match()
    anchors implicitly, which silently dropped the one unanchored pattern (the
    character-mention catch-all the abandonment detector relies on) and cost
    83,427 lines and 560 findings before it was caught against the real log.
    """
    for rx in _COMPILED:
        if rx.search(line):
            return True
    return False


# The faction turn header, for callers that need to split the extract on turn
# boundaries. Pattern 0 by construction — the manifest's order is the analyser's.
TURN_BLOCK_RE = _COMPILED[0]


def is_turn_block(line: str) -> bool:
    """True for the AI-colon-tabs-start faction turn header line."""
    return TURN_BLOCK_RE.search(line) is not None
`;
}

module.exports = { extractAiLog, keepLine, pythonPatternModule, KEEP };
