/**
 * Changelog entries, newest first.
 * Each entry: { version, date, items: [{ type, text }] }
 * Types: "feature", "fix", "improvement", "change"
 *
 * Display versions only — the 4th segment in package.json (e.g. "0.9.2.10") is a
 * silent iteration counter for test builds and is stripped before gating/display.
 *
 * CAP: keep only the last ~5 versions here. WelcomeScreen imports and parses
 * this whole module on every post-update launch, and it had grown to 827KB /
 * 8,623 lines (2026-07-16). When adding a new entry, move the oldest one to
 * docs/changelog-archive.js (npm run ship warns when this file grows past 8).
 */
const CHANGELOG = [
  {
    version: "0.9.1447",
    date: "2026-07-25",
    items: [
      { type: "feature", text: "**The Lab now checks whether your log and your save describe the same moment — and on the reference pair, they do not.** The log covers turns 1-51; the save is turn 102. So every \"the army never arrived\" verdict was being decided against a world **51 turns after the log stopped talking about it** — as long again as the log ever observed. A new provenance check states the relationship and now sits as the FIRST lead, above the findings it qualifies, because a caveat that appears below them has already failed at its job." },
      { type: "improvement", text: "**The gap is a fact, not a guess, because the log is anchored first.** If a log's opening settlement counts match descr_strat's starting ownership, it begins at turn 1 — and only then does \"the save is 51 turns later\" mean anything. On this campaign **218 of 221 factions match (98.6%)**, so the anchor holds. Where it does not hold, the check refuses to compute a gap at all and says the log's turn range cannot be established, rather than doing arithmetic on an assumption." },
      { type: "fix", text: "**Found by chasing a contradiction rather than averaging it away.** The log shows the independent peoples already down to 413 settlements in their very first logged turn and falling; the save shows them holding 522. Both numbers survived scrutiny — the 522 are real named settlements, not placeholders or unresolved owners — which left the pairing itself as the thing that did not hold. The \"conquest is not working\" lead is unaffected as a net statement, but it now carries the caveat, and the modder can see that the net figure may hide a collapse followed by a recovery as factions were wiped out." },
      { type: "improvement", text: "Two guards earned their keep on this change. The worker-safety test caught that the new module was missing from the packaged file list — it would have been **absent from app.asar in the shipped build**, the exact silent failure that whitelist exists to prevent. And the integration test's \"outcome lead must be first\" assertion failed, correctly: that ordering was a deliberate decision, so it was re-argued and updated in place rather than quietly relaxed, with the original intent (outcome above scale) preserved directly beneath." },
    ],
  },

  {
    version: "0.9.1446",
    date: "2026-07-25",
    items: [
      { type: "fix", text: "**Nine fields were being computed on every run and displayed nowhere — and the first one examined turned out to be wrong.** `factionHealth` averaged the engine's \"ungoverned cities N / M\" line, which is written about three times per season, once per AI pass. For most factions the value is stable across those passes (carthage reads 41→41→43, a real settlement count) but for the rebels it *decays within a single season* — 497→450→413 — because its territory is being processed as the passes run. Averaging the two together is meaningless, and it had the rebels holding **79 settlements when they hold about 500**." },
      { type: "improvement", text: "**Now reported as the median of one reading per turn, with an explicit stability flag.** `countIsStable` is computed by comparing the passes' actual values, not by counting samples — a sample count carries no information about agreement, and a first attempt that used one was thrown away for exactly that reason. On the reference campaign **22 of 224 factions are flagged unstable and excluded** (rebels, ptolemaic, seleucid — all mid-conquest), leaving **127 factions with a defensible ungoverned count**: indians 10 of 17, carthage 9 of 36, pontus 6 of 15. The panel names the excluded factions and says why rather than hiding them." },
      { type: "feature", text: "**New \"AI activity\" tab surfaces what the AI actually did.** Orders issued by type, with assault and siege orders coloured apart from movement — the AI issues **8,683 attack-residence and 8,652 siege-residence orders**, so it does order assaults, and a faction that issues none is passive for a different reason than one that issues them and never arrives. Plus the engine's own invasion-target count (a faction reporting zero will never attack however strong it grows), ungoverned settlements, and the rejected script commands. Every section has an explicit empty state, because a section that silently renders nothing makes a parsing regression look like a clean campaign." },
      { type: "improvement", text: "**A contradiction between two sources was chased down rather than averaged over.** The log shows the rebel faction collapsing from 497 settlements to ~30; the save says it *grew* 499 → 522. Rebels cannot do both. Resolved by establishing that the log's figure is not a stable per-turn count for that faction while the save-vs-descr_strat comparison is independent of the log and stands — so the \"conquest is not working\" lead is unaffected. The stability flag now encodes what was learned, so the next reader does not have to re-derive it." },
    ],
  },

  {
    version: "0.9.1445",
    date: "2026-07-25",
    items: [
      { type: "feature", text: "**A failed script command now names the command, the file and the line.** Last release recovered 555 `err: no building of this type in settlement` lines, but that text names nothing you can act on. Each error is now paired with the command that caused it, and cross-referenced against the campaign script — producing one lead: **five `set_building_health` calls at RIS_Campaign_Script.txt lines 4623-4627, each failing exactly 111 times, 555 total.** The suggested fix is the `if SettlementBuildingExists = ...` guard the same script already uses four lines later." },
      { type: "fix", text: "**A parser blind spot found while doing it: the engine sometimes writes console output with NO newline, gluing it onto the end of an AI line.** 111 of the 555 failing commands are hidden that way — the line ends `...num res 0.sudo set_building_health local hinterland_region 100`. Anchoring on `^sudo` missed every one, and worse, it mis-attributed their errors to whichever command came before, inflating one count from 111 to 221. The scan is now unanchored and each error is charged to exactly one command." },
      { type: "improvement", text: "**Three tempting explanations were checked and rejected before this lead was written.** That the building chains don't exist — all four `governmentA`–`D` **are** declared in EDB. That `local` is an unexpanded variable — `local` is correct scope syntax, used properly by the same script seventeen lines earlier. That it's a deliberate try-all-four where three must fail — then one would *succeed*, and all five counts are identical, including a chain that isn't part of any mutually-exclusive set. So the lead reports what is measured (every call fails, always) and does not assert a cause. It also states plainly that these are failure **counts, not rates**: the console echoes only failures, so this log has no denominator." },
      { type: "improvement", text: "**A 5,872-item finding was investigated and deliberately NOT shipped.** `is busy constructing **invalid**` looked like a major defect across 1,077 settlements. Two probes failed to distinguish it from a normal busy settlement, and the one asymmetry found ran *against* the bug reading. Unexplained is not the same as broken, so nothing was published — that would have been 5,872 false accusations. Recorded as ruled-out so it is not re-chased." },
      { type: "improvement", text: "**Guards tightened where this round found them wanting.** The coverage invariant caught real drift (the new command handler made the two counters disagree by exactly 444) but only because I looked — its first version re-implemented the predicate inline, which is precisely the anti-pattern it exists to catch. It now reads both numbers from the same analyser run, and on the reference log they agree exactly at 2,239,227. The sample harvester is now a maintained script (`--write`) that refuses to update the fixture if any pattern lacks a real example, and the reporter's embedded copy is synced from it — 31/31, verified on the frozen build. Extract re-measured rather than estimated: **6.58 MB xz against the 7 MB attachment ceiling**, so it still fits whole, but headroom is now 6% and the next pattern should re-check it." },
    ],
  },

  {
    version: "0.9.1444",
    date: "2026-07-25",
    items: [
      { type: "fix", text: "**The parsing-coverage figure was overstating itself, and finding out why recovered 555 real mod bugs.** `feedLine` opens with a speed guard — `if (line[0] !== 'A') return` — under the comment *every interesting line starts \"AI:\"*. That comment stopped being true when `err: ...` lines (failed script commands) became worth reading: the handler sat below the guard, so it never ran once. The coverage tracker had no such guard and happily counted those lines as parsed. **A coverage number that counts lines the analyser discards is worse than no number, because it reads as reassurance.** The handler moved above the guard, and the tracker's rule now mirrors what `feedLine` can actually reach." },
      { type: "feature", text: "**Recovered by the fix: 555 occurrences of `err: no building of this type in settlement` — a script command aimed at a building the settlement does not have.** Reported as a real mod defect rather than discarded as noise. Also newly counted is the complete mission family, all 11 types: the AI issues **8,683 attack-residence and 8,652 siege-residence orders**, so it genuinely does order assaults. Only `move nonlocal` was read before, which meant the orders that matter most were invisible." },
      { type: "improvement", text: "**Coverage of the 4,386,174-line reference log is now 100.0%, with zero unaccounted lines** (from 21.5% at the start of this work, via 47.1% and 84.9%). Every line is one of three things: parsed signal (2,238,783), recognised vocabulary that carries no signal (1,487,465), or a known subsystem family that is deliberately not read line-by-line (659,926) — and the three are reported apart, so \"recognised\" is never quietly passed off as \"understood\". The last tail was closed by naming the un-prefixed engine notes, asset-loading chatter and the file's own header banner." },
      { type: "improvement", text: "**Two guards so the number cannot drift back into fiction.** The first asserts the invariant the whole metric rests on: any line the tracker calls signal must actually change the analyser's output — that is what failed silently before. On the real log the two counters now agree *exactly*, both at 2,238,783. The second replaces a hand-written test fixture with **one verbatim line per pattern, harvested from the 4.4M-line log**; all 30 patterns were confirmed to have a real example, so none is speculative. Hand-typed fixtures encode what the engine is imagined to emit, and that has already cost this project a falsifier that passed while testing nothing." },
    ],
  },

  {
    version: "0.9.1443",
    date: "2026-07-25",
    items: [
      { type: "fix", text: "**Correcting the headline of v0.9.1435 and 1437: the \"16× gap\" was a unit error, and the real figure is 1.21×.** Those releases compared a campaign's required *strength* against the save's *soldier counts* and concluded that only 3 of 125 factions could ever meet a typical requirement. The justification was a single coincidence — a line reading `allocated str 27,183` sitting near Ptolemaic's 28,246 soldiers. It was exactly that, a coincidence. Newly-parsed lines carry the engine's own accounting of the same quantity, and Ptolemaic's army strength is **589,755** against those 28,246 men. Across 124 comparable factions the strength-to-men ratio runs p25 21.8, median 32.7, p75 59.6, with 76% inside 2× of the median: strength is a derived metric roughly 33× a headcount, not a headcount." },
      { type: "improvement", text: "**With both sides in the engine's own unit the picture is different and far more useful.** The median offensive requirement is 23,902 strength; the median faction reports 19,772 *free* strength — a ratio of **1.21×**, with **86 of 223 factions** clearing it. So the requirement is not absurd, it is close to what a typical faction has spare, and **61% falling short is a closable gap** rather than the impossibility the old framing implied. The lead now says so and points at the two levers that would move it. The result carries its unit on its face, and a test asserts headcounts stay about 33× smaller so a future mix-up fails loudly." },
      { type: "feature", text: "**The Lab now reads the AI's own strategic reasoning — parsing coverage went from 21.5% to 47.1% of the log.** A taxonomy of the 3.36M lines it was throwing away found five high-value shapes. It now parses the AI's self-reported army/free/navy strength; its **invade decisions with the reasons it gave** (\"at war, inferior to enemy\" 11,225 times — the most direct evidence there is for why an AI will not attack); its defend postures; what troops it wants to recruit (656,132 lines, the twin of the build-appetite line it already read); and its per-settlement tax choices with reasons (100,169 extortionate, 54,908 low, 3,755 high)." },
      { type: "improvement", text: "One shape was deliberately left alone: `region control: settlement 'X' has changed from 'A' to 'B'`, 40,685 lines. It reads like a conquest record and is not — the values are production-focus enums, not faction names. Checked before building anything on it. The crash reporter's extract grew with the new patterns and was re-measured rather than assumed: 5.88 MB compressed, still inside the attachment ceiling, so nothing is trimmed and the extract remains equivalent to the full log." },
    ],
  },
  {
    version: "0.9.1442",
    date: "2026-07-25",
    items: [
      { type: "feature", text: "**Drop a crash report's attachment straight into the AI Movement Lab — it now opens compressed logs itself.** The reporter ships its campaign_ai_log extract as a `.txt.xz`, because that is the only way a 330 MB log fits an attachment. Until now the pipeline stopped one step short of useful: the report arrived, and then somebody had to find a 7-Zip and unpack it before Provincia would look at it. `.gz` and `.xz` are now unpacked automatically — `.gz` with Node's own zlib, `.xz` with the Python runtime Provincia already bundles, since Node has no xz." },
      { type: "improvement", text: "**Verified end to end on the real thing, not in principle.** The reporter was run against the 330 MB reference log to produce a genuine 3.24 MB `.xz` attachment, which was then handed to the Lab: identical `logKind`, turn count, **all 6,399 findings in the same order**, and identical save-verified totals (1,207 never-arrived, 402 unaffordable, 1,140 orphaned), 716 mod-file leads, 37 proven-no-route orders, the same 23,902 median strength requirement and the same +23 independents delta. A 3 MB attachment now yields exactly the analysis the 330 MB original does." },
      { type: "improvement", text: "The unpacked copy goes to a temp file rather than memory (these extracts are ~107 MB decompressed) and is removed however the run ends, including on failure. A corrupt archive is reported as such instead of throwing or handing back junk, and if the bundled Python is missing the message says to extract it manually rather than failing obscurely." },
    ],
  },
  {
    version: "0.9.1441",
    date: "2026-07-25",
    items: [
      { type: "fix", text: "**Hardened yesterday's formations rule against the mistake I nearly made with it a third time.** Chasing the still-unexplained parse failure in descr_formations_ai.txt, I found `unit_density loose` (20 uses in RIS, **0 in vanilla**) and `block_formation square` (4 in RIS, 0 in vanilla) and was about to report both as defects. The file's own header documents them: *\"unit_density — either loose or close\"* and *\"block_formation — the formation to organise the block into (square, column, line)\"*. **Absence from vanilla is not evidence of invalidity.** So the rule now grades by confidence: a token that is a near miss of a real one — a dropped prefix or typo, which is the `pilum_infantry` case the engine confirmed 413 times — stays an error, while a wholly novel token is a warning that says plainly it may be a deliberate extension and points at the game's own error_log as the thing that would settle it." },
      { type: "feature", text: "**New check: `unit_density` and `block_formation` values are validated against the list the file's own header documents** — better evidence than vanilla usage, and it would catch a plain typo like `unit_density sparse`. 536 values checked on the real mod, 0 bad, which is the correct answer and confirms `loose` and `square` pass. `unit_formation` is deliberately not checked: its documented list ends in \"(wedge, square, ...)\", and an open-ended list cannot be validated without inventing the rest." },
      { type: "improvement", text: "Ruled out, so nobody re-chases it: the line-2369 parse failure is **not** caused by any of these. That formation contains zero bare `pilum_infantry`, no `unit_density loose` and no `block_formation square`, and every token it uses is one vanilla uses too. It remains a separate, unexplained defect — which is now recorded as such rather than being quietly attached to a nearby finding." },
    ],
  },
  {
    version: "0.9.1440",
    date: "2026-07-25",
    items: [
      { type: "feature", text: "**Mod Lint now catches the defect that took 32 crashed play sessions to find — statically, in 220ms.** The v7.12 beta telemetry showed the engine rejecting a formation token **413 times across 32 sessions**, in its own words: `Failed to find either a unit class or unit category. Provided: 'pilum_infantry'`, alongside 462 unit-enum asserts and 2,893 `is_template_formation()` failures. descr_formations_ai.txt was also the file named by 352 script faults — five times the next worst. The lint now reads that file and reports the one line at fault: bare `pilum_infantry`, 28 uses from line 78, where the engine only knows the prefixed forms." },
      { type: "improvement", text: "**The vocabulary is derived from vanilla, not invented — and that is what makes it trustworthy.** My first pass at this assumed every underscore-joined token was a mod invention and would have condemned **192 lines**. Checking the three shipped vanilla files disproved it outright: `heavy_pilum_infantry`, `light_pilum_infantry`, `spearmen_pilum_infantry`, `non_phalanx_spear`, `ranged_missile_infantry`, `chanting_screeching`, `phalanx`, `swimming` and `carrying_siege_engine *` are all tokens vanilla itself uses. Only the bare form is absent — 0 uses across all three vanilla files against 28 in RIS, and precisely the token the engine names. Guessing would have produced 164 false accusations; on the real mod the rule now reports exactly one finding out of 819 tokens examined." },
      { type: "improvement", text: "The message quotes the engine's own wording so it can be grepped straight against a log, names the near-miss (\"vanilla does use heavy_pilum_infantry — a dropped prefix is the likely cause\"), and the check reports how many tokens it examined so a rule that silently stops working is detectable rather than looking like a clean file. Every vanilla token is unit-tested as a non-finding, which is the false-positive trap this rule could easily have fallen into." },
    ],
  },
  ];

export default CHANGELOG;
