# GENERATED by scripts/gen-ailog-patterns.js — DO NOT EDIT BY HAND.
#
# The line shapes Provincia's AI Movement Lab reads out of campaign_ai_log.txt,
# exported from AI_RX in src/aiMovementAnalyzer.js so the reporter's filter can
# never drift from the analyser's. A drifted copy would silently drop data with
# no error — the first hand-written version guessed the faction turn header as
# "+start" instead of "AI: <tabs>start" and matched nothing at all.
#
# JavaScript and Python regex syntax agree for every construct used here
# (anchors, \t, character classes, escaped parens, \d, \w, \S, +, *, ?).
# scripts/gen-ailog-patterns.js asserts that before writing this file.
import re

AI_LOG_LINE_PATTERNS = [
    r"""^AI: \t*start '([^']+)' for year (-?\d+), season (\w+)""",
    r"""^AI: campaign: mission move nonlocal: char '([^']+)' moving towards sett '([^']+)', priority (\d+)""",
    r"""^AI: named cc: (?:character|army) '([^']+)' told to move to '([^']+)', priority (\d+)""",
    r"""^AI: campaign: res for char '([^']+)' assigned to reg (\d+) at priority (\d+)""",
    r"""^AI: resource for char '([^']+)' released by controller""",
    r"""^AI: campaign for region '(\d+)' aborted because of insufficient available strength""",
    r"""^AI: campaign: campaign for '([^']+)' \(reg (\d+), des \d+\) using strategy (ACS_\w+)\. required str (\d+) \(ACZ_\w+\), allocated str (\d+)""",
    r"""^AI: finance: est income (-?\d+), est maintenance (-?\d+), est outgoings (-?\d+) -- spending max (-?\d+), spending norm (-?\d+); balance (\w+), state (AFS_\w+)""",
    r"""^AI: -- building '([^']+)' at priority (\d+)""",
    r"""^AI: campaign: garrison of settlement '([^']+)' told to split, (\d+) units leaving, priority (\d+)""",
    r"""^AI: mildir: \S+ attack authorised against '([^']+)'""",
    r"""^AI: (\d+) (spies|assassins) assigned this turn""",
    r"""^AI: ltgd: army strength (\d+), free army strength (\d+), navy strength (\d+)""",
    r"""^AI: ltgd: '([^']+)' invade '([^']+)', (.+?) >> (ALI_\w+) \((\d+)\)""",
    r"""^AI: ltgd: defend \([^)]*\) vs fac '([^']+)': (.+?) >> (ALD_\w+)""",
    r"""^AI: -- troop type '([^']+)' at priority (\d+)""",
    r"""^AI: region control: settlement '([^']+)', \(pop (\d+), old order (-?\d+)\), tax (TAX_LEVEL_\w+) due to (.+?)\.?$""",
    r"""^AI: production: started recruitment of '([^']+)' at '([^']+)', priority (\d+), prod type (AI_PROD_\w+)""",
    r"""^AI: production: started '([^']+)' at '([^']+)', priority (\d+), prod type (AI_PROD_\w+)""",
    r"""^AI: ltgd: number of invasion targets: (\d+)""",
    r"""^AI: number of spies (\d+), number of assassins (\d+)""",
    r"""^AI: named cc: leader status '([^']+)', heir status '([^']+)', ungoverned cities (\d+) \/ (\d+), adoptees (\d+), resources (\d+) \(total str (\d+)\)""",
    r"""^AI: production: settlement '([^']+)' is busy constructing (.+?), considering repairs""",
    r"""^AI: campaign: mission ([a-z]+(?: \([a-z]+\)| [a-z]+)*): """,
    r"""^AI: worldwide: char '([^']+)' assigned \(in region (\d+)\) at priority (\d+)""",
    r"""^AI: resource for char '([^']+)' released by worldwide controller in region (\d+)""",
    r"""^AI: Diplomat CC: Character "([^"]+)" told to move to settlement "([^"]+)"\. Task: (\w+)\. Initiate: (\w+)\. Priority (\d+)""",
    r"""^AI: production: (sufficient numbers of troops[^.]*|not enough cash[^.]*|no more useful[^.]*)\.?$""",
    r"""^\s*err: (.+?)\s*$""",
    r"""sudo ([a-z_]+)((?: [^\s]+)*)\s*$""",
    r"""char '([^']+)'|character '([^']+)'|army '([^']+)'""",
]

_COMPILED = [re.compile(p) for p in AI_LOG_LINE_PATTERNS]


def keep_ai_log_line(line: str) -> bool:
    """True when Provincia's analyser would read this line.

    search(), NOT match(). JavaScript's RegExp.test() scans the whole string; the
    patterns that must be anchored carry their own leading ^. Python's match()
    anchors implicitly, which silently dropped the one unanchored pattern (the
    character-mention catch-all the abandonment detector relies on) and cost
    83,427 lines and 560 findings before it was caught against the real log.
    """
    for rx in _COMPILED:
        if rx.search(line):
            return True
    return False


# The faction turn header, for callers that need to split the extract on turn
# boundaries. Pattern 0 by construction — the manifest's order is the analyser's.
TURN_BLOCK_RE = _COMPILED[0]


def is_turn_block(line: str) -> bool:
    """True for the AI-colon-tabs-start faction turn header line."""
    return TURN_BLOCK_RE.search(line) is not None
